name: Docs
on:
  push:
    branches: [master]
jobs:
  build:
    name: "Documentation build"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install toolchain
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer
      - name: Install dependencies
        run: composer update --optimize-autoloader --ignore-platform-reqs

      - name: Set Git author
        run: git config --global user.name "github-actions[bot]" && git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Clone site repo
        uses: actions/checkout@v2
        with:
          repository: SOF3/InfoAPI
          ssh-key: ${{secrets.SITE_KEY}}
          path: docs

      - name: Build documentation
        run: php runTool.php DocGenerator
      - run: cp README.md docs/README.md

      - name: Git commit
        run: git add -A && git commit -m "Documentation build for SOF3/InfoAPI@${{github.sha}}"
        working-directory: docs
      - name: Push pages
        run: git push
        working-directory: docs
